# Generated by Django 4.1.1 on 2022-10-04 11:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("wagtailimages", "0024_index_image_file_hash"),
        ("wagtailcore", "0077_alter_revision_user"),
        ("buyhouse", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(model_name="buyhousepage", name="subtitle",),
        migrations.RemoveField(model_name="sellhousepage", name="button_text",),
        migrations.RemoveField(model_name="sellhousepage", name="description",),
        migrations.RemoveField(model_name="sellhousepage", name="external_page",),
        migrations.RemoveField(model_name="sellhousepage", name="internal_page",),
        migrations.RemoveField(model_name="sellhousepage", name="service_image",),
        migrations.AddField(
            model_name="buyhousepage",
            name="button_text",
            field=models.CharField(blank=True, max_length=40),
        ),
        migrations.AddField(
            model_name="buyhousepage",
            name="description",
            field=models.TextField(blank=True, max_length=440),
        ),
        migrations.AddField(
            model_name="buyhousepage",
            name="external_page",
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name="buyhousepage",
            name="internal_page",
            field=models.ForeignKey(
                blank=True,
                help_text="Select a wagtail internal page",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="+",
                to="wagtailcore.page",
            ),
        ),
        migrations.AddField(
            model_name="buyhousepage",
            name="service_image",
            field=models.ForeignKey(
                help_text="this image will be used on th service Listing page and will be cropped to 570px by 370px",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="+",
                to="wagtailimages.image",
            ),
        ),
        migrations.AddField(
            model_name="sellhousepage",
            name="subtitle",
            field=models.TextField(blank=True, max_length=500),
        ),
    ]
