# Generated by Django 4.1.1 on 2022-10-04 11:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("wagtailimages", "0024_index_image_file_hash"),
        ("wagtailcore", "0077_alter_revision_user"),
        ("buyhouse", "0003_buyhousepage_body"),
    ]

    operations = [
        migrations.RemoveField(model_name="buyhousepage", name="external_page",),
        migrations.RemoveField(model_name="buyhousepage", name="internal_page",),
        migrations.RemoveField(model_name="buyhousepage", name="service_image",),
        migrations.AddField(
            model_name="buyhousepage",
            name="banner_background_image",
            field=models.ForeignKey(
                blank=True,
                help_text="The banner background image",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="+",
                to="wagtailimages.image",
            ),
        ),
        migrations.AddField(
            model_name="buyhousepage",
            name="button",
            field=models.ForeignKey(
                blank=True,
                help_text="Select an optional page to link to",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="+",
                to="wagtailcore.page",
            ),
        ),
        migrations.AlterField(
            model_name="buyhousepage",
            name="button_text",
            field=models.CharField(
                default="Read More", help_text="Button Text", max_length=50
            ),
        ),
    ]
