# Generated by Django 4.1.1 on 2022-09-25 23:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("wagtailimages", "0024_index_image_file_hash"),
        ("wagtailcore", "0077_alter_revision_user"),
        ("home", "0002_create_homepage"),
    ]

    operations = [
        migrations.AddField(
            model_name="homepage",
            name="banner_background_image",
            field=models.ForeignKey(
                help_text="The banner background image",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="+",
                to="wagtailimages.image",
            ),
        ),
        migrations.AddField(
            model_name="homepage",
            name="button",
            field=models.ForeignKey(
                blank=True,
                help_text="Select an optional page to link to",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="+",
                to="wagtailcore.page",
            ),
        ),
        migrations.AddField(
            model_name="homepage",
            name="button_text",
            field=models.CharField(
                default="Read More", help_text="Button Text", max_length=50
            ),
        ),
        migrations.AddField(
            model_name="homepage",
            name="lead_text",
            field=models.CharField(
                blank=True,
                help_text="Subheading text under the banner title",
                max_length=140,
            ),
        ),
    ]
